runtime: python310
entrypoint: gunicorn -b :$PORT app:app
instance_class: F2

env_variables:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"

handlers:
- url: /static
  static_dir: Static
- url: /.*
  script: auto
